#!/bin/bash
for i in $(virsh list --all | sed 1,2d |awk '{print $2}'); do printf $i,; printf $(virsh dumpxml $i | grep nova:name), ; j=$(virsh dumpxml $i | grep '/dev/disk/' | cut -d "'" -f2); if [ -e "$j" ]; then ls -l $j | awk '{print $11}'; else echo "noDiskPath"; fi; done
